# Change these first
owner: masterkoppa # Your GitHub username
repo: UptimeMonitor # Your Github repository name

# Add your sites here
sites:
  - name: Google
    url: https://www.google.com
  - name: SmugMug Site
    url: https://masterkoppa.smugmug.com
  - name: Personal Site
    url: https://aruiz.io
  - name: Personal Site (www)
    url: https://www.aruiz.io/blog
  - name: Personal Site (alt)
    url: https://andresjruiz.com
  - name: Beyond the Tales
    url: https://beyondthetales.com
  - name: NightOwl
    url: https://codename-nightowl.com

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /UptimeMonitor/
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Personal Health Dashboard
  introTitle: "Personal Health Dashboard, powered by [**Upptime**](https://github.com/upptime/upptime)"
  introMessage: A custom personal health dashboard to monitor domains.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "*/15 * * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
